---
- name: "PLAY 1: BACKUP device"
  connection: network_cli
  hosts: all
  tasks:
    - name: "TASK 1: Include tasks for different devices"
      include_tasks: "tasks/{{ ansible_network_os }}.yml"

    - name: "TASK 3: Create outputs/folder"
      file:
        path: "outputs"
        state: directory
      run_once: true

    - name: "TASK: Get facts"
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"      
   
    - name: "TASK: Get date"
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: "TASK 4: Write output to file"
      copy:
        content: "{{ cli_result.stdout[0] }}\n"
        dest: "outputs/{{ DTG }}-{{ inventory_hostname }}.txt"
